Created ListView for ban phase
TheSuperNooby/PyPlanet pull request #1
Opened 2020-03-03 20:37 UTC by TheSuperNoob

Will edit with checklist later

2020-03-04 22:09 UTC, JosVroegindeweij commented
- [ Banning order chat statement ] 

- [ Look into aesthetics of replacing Player by [x/4] ]

- [ Wait x seconds before walls of text are being sent (includes printing out this timer) ] 

- [ matchend command should have chat output ] 

- [ Documentation of code ]

2020-03-05 18:45 UTC, TheSuperNoob commented on pyplanet/apps/contrib/brawl_match/__init__.py
> +			await self.instance.chat(f'{self.chat_prefix}' + message)
`await self.instance.chat(f'{self.chat_prefix} {message}', player`
and 
`await self.instance.chat(f'{self.chat_prefix} {message}'`

2020-03-05 18:52 UTC, TheSuperNooby approved these changes
This is looking good for a first rough version. 
It will work fine for the matches this weekend with an admin keeping an eye on things.

Ill approve this for now so we can land it and get it ready for the matches.

2020-03-05 18:58 UTC, JosVroegindeweij requested changes

2020-03-05 18:58 UTC, JosVroegindeweij commented on pyplanet/apps/contrib/brawl_match/__init__.py
> +			await self.instance.chat(f'{self.chat_prefix}' + message, player)
```suggestion
			await self.instance.chat(f'{self.chat_prefix}{message}', player)
```

2020-03-05 19:01 UTC, JosVroegindeweij requested changes

2020-03-05 19:01 UTC, JosVroegindeweij commented on pyplanet/apps/contrib/brawl_match/__init__.py
>  			await self.instance.chat(f'{self.chat_prefix}' + message)
```suggestion
			await self.instance.chat(f'{self.chat_prefix}{message}')
```

2020-03-05 21:52 UTC, TheSuperNoob commented on pyplanet/apps/contrib/brawl_match/__init__.py
>  		self.match_players = []
Put all this in an else statement and you can remove the empty return statement

2020-03-05 22:06 UTC, JosVroegindeweij commented on pyplanet/apps/contrib/brawl_match/__init__.py
>  		self.match_players = []
I don't think that would be an improvement. More if-else statements are making code less readable. An 'if cond: return' statement is quite a readable way of saying: In this case the method should not be executed.

2020-03-06 07:46 UTC, TheSuperNoob commented on pyplanet/apps/contrib/brawl_match/__init__.py
>  		self.match_players = []
Maybe it's just me, but i prefer if at any part in a method you have a return statement then every reachable part of the method should end in a return also. In Python every method returns something. So in this case `return` is identical to `return None` which is the same as just not saying anything.

2020-03-06 07:56 UTC, JosVroegindeweij commented on pyplanet/apps/contrib/brawl_match/__init__.py
>  		self.match_players = []
Maybe it's just me, but I don't think it's important ;) I value readability more. Also, when a `return` statement is absent in a method, the method will return `None`. So it's equivalent to use `return` as to not return anything at all

2020-03-06 08:12 UTC, TheSuperNoob commented on pyplanet/apps/contrib/brawl_match/__init__.py
> +			self.match_tasks.append(asyncio.create_task(func()))
Is this check needed?I think this will still work if you just have `self.match_tasks.append(asyncio.create_task(func(*args)))`

2020-03-06 09:46 UTC, JosVroegindeweij requested changes

2020-03-06 09:46 UTC, JosVroegindeweij commented on pyplanet/apps/contrib/brawl_match/__init__.py
> +		asyncio.ensure_future(self.instance.gbx('NextMap'))
```suggestion
		await self.instance.gbx('NextMap')
```

2020-03-06 09:51 UTC, JosVroegindeweij approved these changes

2020-03-06 09:58 UTC, merged